name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          # 5.1
         - wp_docker_tag: 5.1-php7.3-apache
           php_version: 7.3
          # 5.2
         - wp_docker_tag: 5.2-php7.3-apache
           php_version: 7.3
          # 5.3
         - wp_docker_tag: 5.3-php7.3-apache
           php_version: 7.3
         - wp_docker_tag: 5.3-php7.4-apache
           php_version: 7.4
          # 5.4
         - wp_docker_tag: 5.4-php7.3-apache
           php_version: 7.3
         - wp_docker_tag: 5.4-php7.4-apache
           php_version: 7.4
          # 5.5
         - wp_docker_tag: 5.5-php7.3-apache
           php_version: 7.3
         - wp_docker_tag: 5.5-php7.4-apache
           php_version: 7.4
          # 5.6
         - wp_docker_tag: 5.6-php7.3-apache
           php_version: 7.3
         - wp_docker_tag: 5.6-php7.4-apache
           php_version: 7.4
         - wp_docker_tag: 5.6-php8.0-apache
           php_version: 8.0
          # 5.7
         - wp_docker_tag: 5.7-php7.3-apache
           php_version: 7.3
         - wp_docker_tag: 5.7-php7.4-apache
           php_version: 7.4
         - wp_docker_tag: 5.7-php8.0-apache
           php_version: 8.0
          # 5.8
         - wp_docker_tag: 5.8-php7.3-apache
           php_version: 7.3
         - wp_docker_tag: 5.8-php7.4-apache
           php_version: 7.4
         - wp_docker_tag: 5.8-php8.0-apache
           php_version: 8.0
      fail-fast: false
    env:
      WP_DOCKER_TAG: ${{ matrix.wp_docker_tag }}
    steps:
      - uses: actions/checkout@v1

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          extensions: zip

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Setup docker
        run: docker-compose up -d

      - name: Create config file
        run: touch .env.testing

      - name: Check running containers
        run: docker ps -a

      - name: Fix permissions
        run: >
          docker exec
          -w /var/www/html
          disable-customizer_wordpress_1 bash
          -c "sudo chown -R www-data:www-data /var/www/html && sudo chmod -R 775 /var/www/html"
          
      - name: Wait until the server is up
        run: npx wait-on http://localhost/wp-login.php --verbose --timeout 60000

      - name: Run test suite
        run: >
          docker exec
          -w /var/www/html/wp-content/plugins/disable-customizer
          -e WP_ROOT_FOLDER
          -e TEST_SITE_WP_ADMIN_PATH
          -e TEST_SITE_DB_NAME
          -e TEST_SITE_DB_HOST
          -e TEST_SITE_DB_USER
          -e TEST_SITE_DB_PASSWORD
          -e TEST_SITE_DB_PASSWORD
          -e TEST_SITE_TABLE_PREFIX
          -e TEST_SITE_WP_URL
          -e TEST_SITE_WP_DOMAIN
          -e TEST_SITE_ADMIN_EMAIL
          -e TEST_SITE_ADMIN_USERNAME
          -e TEST_SITE_ADMIN_PASSWORD
          disable-customizer_wordpress_1 bash
          -c './vendor/bin/codecept run acceptance --fail-fast --debug'
        env:
          WP_ROOT_FOLDER: /var/www/html
          TEST_SITE_WP_ADMIN_PATH: /wp-admin
          TEST_SITE_DB_NAME: exampledb
          TEST_SITE_DB_HOST: db
          TEST_SITE_DB_USER: exampleuser
          TEST_SITE_DB_PASSWORD: examplepass
          TEST_SITE_TABLE_PREFIX: wp_
          TEST_SITE_WP_URL: http://wordpress
          TEST_SITE_WP_DOMAIN: wordpress
          TEST_SITE_ADMIN_EMAIL: example@example.com
          TEST_SITE_ADMIN_USERNAME: admin
          TEST_SITE_ADMIN_PASSWORD: admin

      - name: Upload artifact
        if: failure()
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Test output ${{ matrix.wp_docker_tag }}
          path: tests/_output/
